[package]
name = "sane-fmt"
version = "0.1.0"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "^0.3.14"
dprint-plugin-typescript = "^0.15.0"
difference = "^2.0.0"
relative-path = "^1.0.0"
ansi_term = "^0.12.1"

[dev-dependencies]
tempfile = "^3.1.0"
strip-ansi-escapes = "^0.1.0"
