[package]
name = "sane-fmt"
description = "Opinionated code formatter for TypeScript and JavaScript"
version = "0.2.11"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
license = "MIT"
edition = "2018"
keywords = ["format", "typescript", "javascript"]
categories = ["command-line-utilities"]
repository = "https://github.com/KSXGitHub/sane-fmt.git"
include = [
  "/src",
  "/Cargo.toml"
]

[dependencies]
structopt = "^0.3.14"
dprint-plugin-typescript = "^0.16.1"
difference = "^2.0.0"
relative-path = "^1.0.0"
ansi_term = "^0.12.1"

[dev-dependencies]
tempfile = "^3.1.0"
strip-ansi-escapes = "^0.1.0"
fs_extra = "^1.1.0"
serde = "^1.0.106"
serde_json = "^1.0.52"
toml = "^0.5.6"
