name: Test

on:
  - push
  - pull_request

env:
  PNPM_VERSION: 4.14.0

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        rust:
          - '1.43.0'
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Rust Cargo Registry
        uses: actions/cache@v1.1.2
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: ~/.cargo/registry
          key: 0-${{ github.job }}-cargo-registry-${{ matrix.rust }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            0-${{ github.job }}-cargo-registry-${{ matrix.rust }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
            0-${{ github.job }}-cargo-registry-${{ matrix.rust }}-${{ runner.os }}-

      - name: Cache Rust Cargo Index
        uses: actions/cache@v1.1.2
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: ~/.cargo/git
          key: 0-${{ github.job }}-cargo-index-${{ matrix.rust }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            0-${{ github.job }}-cargo-index-${{ matrix.rust }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
            0-${{ github.job }}-cargo-index-${{ matrix.rust }}-${{ runner.os }}-

      - name: Cache Rust Build
        uses: actions/cache@v1.1.2
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: target
          key: 0-${{ github.job }}-build-${{ matrix.rust }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            0-${{ github.job }}-build-${{ matrix.rust }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
            0-${{ github.job }}-build-${{ matrix.rust }}-${{ runner.os }}-

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: 'true'
          default: 'true'

      - name: Build
        run: cargo build --locked

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache PNPM store
        uses: actions/cache@v1.1.2
        with:
          path: ~/.pnpm-store
          key: create-release-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            create-release-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
            create-release-pnpm-store-

      - name: Install PNPM
        run: ./ci/install-pnpm.sh

      - name: Install Node.js dependencies
        run: pnpm recursive install

      - name: Compile TypeScript
        run: ./compile-typescript.sh

      - name: Test
        run: cargo test

  clippy_check:
    name: Clippy

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        rust:
          - '1.43.0'
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Rust Cargo Registry
        uses: actions/cache@v1.1.2
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: ~/.cargo/registry
          key: 0-${{ github.job }}-cargo-registry-${{ matrix.rust }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            0-${{ github.job }}-cargo-registry-${{ matrix.rust }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
            0-${{ github.job }}-cargo-registry-${{ matrix.rust }}-${{ runner.os }}-

      - name: Cache Rust Cargo Index
        uses: actions/cache@v1.1.2
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: ~/.cargo/git
          key: 0-${{ github.job }}-cargo-index-${{ matrix.rust }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            0-${{ github.job }}-cargo-index-${{ matrix.rust }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
            0-${{ github.job }}-cargo-index-${{ matrix.rust }}-${{ runner.os }}-

      - name: Cache Rust Build
        uses: actions/cache@v1.1.2
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: target
          key: 0-${{ github.job }}-build-${{ matrix.rust }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            0-${{ github.job }}-build-${{ matrix.rust }}-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
            0-${{ github.job }}-build-${{ matrix.rust }}-${{ runner.os }}-

      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: clippy
          override: 'true'
          default: 'true'

      - name: Use clippy to lint code
        uses: actions-rs/clippy-check@v1
        with:
          name: Clippy Report (${{ matrix.rust }}, ${{ matrix.os }})
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all-targets -- -D warnings

  fmt_check:
    name: Fmt

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        rust:
          - '1.43.0'
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt
          override: 'true'
          default: 'true'

      - name: Check code formatting
        run: cargo fmt -- --check
